# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_helperprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
