# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_helperpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helperpicture',
            name='image',
            field=models.ImageField(upload_to=b'pictures'),
        ),
    ]
